---
- name: Tarea SCM - Instalacion del navegador Chromium (SOLUCION FINAL CON PPA)
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: 1. Asegurar la instalación de 'software-properties-common' para manejar PPA
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: 2. Añadir PPA para obtener versión de Chromium que no es SNAP
      ansible.builtin.apt_repository:
        repo: 'ppa:chromium-team/stable' # PPA del equipo Chromium
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: ppa_result

    - name: 3. Intentar instalar 'chromium-browser' via APT desde PPA
      ansible.builtin.apt:
        name: chromium-browser
        state: present
        update_cache: yes
        force_apt_get: yes
      when: ansible_os_family == "Debian"
      register: final_apt_result

    - name: 4. Verificar la instalacion y registrar el binario
      ansible.builtin.shell: which chromium-browser
      register: verificacion_final
      ignore_errors: yes
    
    - name: 5. Informar el resultado final de la instalacion
      ansible.builtin.debug:
        msg: |
          ==========================================================
          INSTALACIÓN FINALIZADA en {{ inventory_hostname }}.
          Estado: 
            - ÉXITO: {{ 'Sí' if verificacion_final is success else 'No' }}
            - Método Usado: PPA/APT
          Detalles de la Verificación: {{ verificacion_final.stdout if verificacion_final is success else 'Fallo. El host no acepta el PPA.' }}
          ==========================================================
