---
- name: Tarea SCM - Instalacion del navegador Chromium (Usando SNAP)
  hosts: all
  gather_facts: yes
  become: yes # NECESARIO para instalar snap

  tasks:
    - name: 1. Asegurar que snapd este instalado y actualizado
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: 2. Instalar el navegador Chromium usando el módulo snap
      community.general.snap:
        name: chromium
        state: present
        classic: yes # Usa modo clásico para instalación completa
      when: ansible_os_family == "Debian"
    
    - name: 3. Verificar instalacion (Comando de shell)
      ansible.builtin.shell: which chromium
      register: verificacion_chromium
      ignore_errors: yes

    - name: 4. Informar el resultado
      ansible.builtin.debug:
        msg: |
          ==========================================================
          Instalacion de Chromium (SNAP) finalizada en {{ inventory_hostname }}.
          Estado: {{ 'ÉXITO' if verificacion_chromium is success else 'FALLÓ - La instalacion de paquetes no pudo completarse' }}
          Ruta: {{ verificacion_chromium.stdout }}
          ==========================================================
