---
- name: Tarea SCM - Instalacion del navegador Chromium
  hosts: all
  gather_facts: yes
  become: yes  # ¡NECESARIO para ejecutar apt (sudo)!

  tasks:
    - name: Asegurar que el paquete 'chromium-browser' este instalado
      ansible.builtin.apt:
        name: chromium-browser
        state: present
        update_cache: yes
      # Esta condicion es una buena practica para asegurar que solo se ejecute
      # en sistemas Debian/Ubuntu/Zorin
      when: ansible_os_family == "Debian"

    - name: Verificar la instalacion buscando el binario
      ansible.builtin.command: dpkg -L chromium-browser
      register: verificacion_chromium
      ignore_errors: yes # Si falla, es porque no se instaló, no un error fatal

    - name: Informar el resultado de la instalacion
      ansible.builtin.debug:
        msg: |
          Instalacion finalizada en {{ inventory_hostname }}.
          Estado: {{ 'ÉXITO' if verificacion_chromium is success else 'FALLÓ' }}
          Ruta del binario: {{ verificacion_chromium.stdout_lines[0] if verificacion_chromium is success and verificacion_chromium.stdout_lines else 'No encontrado.' }}
