---
- name: Tarea SCM - Instalacion del navegador Chromium
  hosts: all
  gather_facts: yes
  become: yes # NECESARIO para que el usuario 'ansible_svc' ejecute comandos con privilegios (apt)

  tasks:
    - name: 1. Limpiar y corregir dependencias rotas (Soluciona E: Unable to correct problems)
      ansible.builtin.apt:
        state: full-upgrade # Actualiza e intenta corregir dependencias y paquetes rotos
        force_apt_get: yes  # Fuerza el uso de apt-get
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: 2. Asegurar que el paquete 'chromium-browser' este instalado
      ansible.builtin.apt:
        name: chromium-browser
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: 3. Verificar la instalacion buscando el binario (dpkg)
      ansible.builtin.command: dpkg -L chromium-browser
      register: verificacion_chromium
      ignore_errors: yes # Si falla la busqueda, no detiene el playbook
    
    - name: 4. Informar el resultado de la instalacion
      ansible.builtin.debug:
        msg: |
          ==========================================================
          Instalacion de Chromium finalizada en {{ inventory_hostname }}.
          Estado de la Tarea: {{ 'ÉXITO' if verificacion_chromium is success else 'FALLÓ - La instalacion de paquetes no pudo completarse' }}
          ==========================================================
