---
- name: Tarea SCM - Instalacion del navegador Firefox (Alternativa a Chromium)
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: 1. Asegurar la instalación de Firefox via APT
      ansible.builtin.apt:
        name: firefox
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: firefox_install

    - name: 2. Forzar limpieza y corrección de dependencias rotas
      ansible.builtin.shell: apt --fix-broken install -y && apt autoclean
      when: ansible_os_family == "Debian" and firefox_install is failed
      
    - name: 3. Reintentar la instalación de Firefox si falló la limpieza
      ansible.builtin.apt:
        name: firefox
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and firefox_install is failed
      register: firefox_install_retry

    - name: 4. Verificar la instalacion y registrar el binario
      ansible.builtin.shell: which firefox
      register: verificacion_final
      ignore_errors: yes
    
    - name: 5. Informar el resultado final
      ansible.builtin.debug:
        msg: |
          ==========================================================
          INSTALACIÓN FINALIZADA en {{ inventory_hostname }}.
          Navegador Instalado: Firefox
          Estado: {{ 'ÉXITO' if verificacion_final is success else 'FALLÓ' }}
          Detalles: {{ verificacion_final.stdout if verificacion_final is success else 'Fallo al localizar el binario de Firefox.' }}
          ==========================================================
