---
- name: Tarea SCM - Instalacion de la utilidad 7zip (p7zip-full)
  hosts: all
  gather_facts: yes
  become: yes # Necesario para usar el gestor de paquetes apt

  tasks:
    - name: 1. Asegurar la instalacion del paquete 'p7zip-full'
      ansible.builtin.apt:
        name: p7zip-full
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: install_result

    - name: 2. Verificar la instalacion buscando el binario '7z'
      ansible.builtin.shell: which 7z
      register: verificacion_7z
      ignore_errors: yes
    
    - name: 3. Informar el resultado de la instalacion
      ansible.builtin.debug:
        msg: |
          ==========================================================
          INSTALACIÓN DE 7-Zip (p7zip-full) en {{ inventory_hostname }}.
          Estado: {{ 'ÉXITO' if verificacion_7z is success else 'FALLÓ' }}
          Detalles: {{ verificacion_7z.stdout if verificacion_7z is success else 'El binario 7z no se encontró. Revisar Tarea 1.' }}
          ==========================================================
